/* generated by scripts/emit.mjs — edit src/client, not this file */
window.__ModuleLoader__.load({
	id: "dsh-cursor-acp",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		const React = require("react");
		const zh = {
		    nav: 'Cursor 子代理',
		    title: 'Cursor 子代理',
		    intro: '把本机已登录的 Cursor 命令行当成子代理。对话还在 DeepSeek Harness，任务会交给 Cursor。这不是模型列表里的「Cursor 模型」，也不是 Cursor 官方产品。',
		    proxyHint: '国内请注意：浏览器开了代理，终端里的 agent / dsh 默认仍直连。先在同一窗口设置 HTTPS_PROXY 和 NODE_USE_ENV_PROXY=1，再登录、再启动。详见项目 README「国内网络」。',
		    found: '已找到 Cursor 命令行。对话里会出现工具 cursor_agent。找到命令行不等于已经登录。',
		    missing: '未找到 Cursor 命令行。请先安装，再登录，然后重启 DeepSeek Harness。',
		    installWin: 'PowerShell 安装：irm \'https://cursor.com/install?win32=true\' | iex',
		    installUnix: '安装：curl https://cursor.com/install -fsS | bash',
		    login: '还要在终端执行 agent login（或设置 CURSOR_API_KEY）。没登录或代理不通时，派活会失败。',
		    signedIn: '已登录。派活可以走 cursor_agent。',
		    signedOut: '命令行在，但还没登录。请在终端执行 agent login（或设置 CURSOR_API_KEY），然后重启 DeepSeek Harness。',
		    loginUnknown: '查不到登录状态。若派活失败，先在终端跑 agent status；国内还要检查代理。',
		    proxyMissing: '当前进程没有 HTTPS_PROXY。浏览器开了代理也不算。国内请在启动 dsh 的同一窗口先设代理和 NODE_USE_ENV_PROXY=1。',
		    proxyPartial: '已经有代理地址，但没设 NODE_USE_ENV_PROXY=1，Node 可能仍直连。',
		    proxyClashDirect: 'Clash 可能把 node.exe 设成了直连，子进程可能没走代理。请让 node.exe / agent 走代理，不要设成 DIRECT。',
		    hostPluginMissing: '当前这份 dsh 找不到官方子代理包，cursor_agent 没有挂上。需要带 @deepseek-ai/dsh-subagent-acp 和 dsh-tool-subagent 的 dsh。',
		    probe: '测一下',
		    probeHelp: '派一个只读的最小任务（官方 agent --print --mode ask，回复 pong）。会用一点 Cursor 额度。',
		    probeRunning: '正在测…',
		    probeOk: '通了。命令行已登录，也能接到 Cursor。',
		    probeFail: '不通。请看上面的登录/代理提示，或在终端跑 agent status。',
		    probeMissing: '还没找到命令行，没法测。',
		    probeSignedOut: '还没登录，测不了。请先 agent login。',
		    probeTimeout: '等太久没有结果。国内请先检查代理，再点一次。',
		    command: '可执行文件',
		    loading: '正在检测…',
		    failed: '无法读取状态。',
		    picker: '子代理模型',
		    pickerHelp: '只影响 cursor_agent。选法和 Cursor 一样：思考程度、Fast、模型。选好后点应用，下一轮才会换。auto 跟 CLI 默认走。',
		    effort: '思考程度',
		    effortLow: '低',
		    effortMedium: '中',
		    effortHigh: '高',
		    effortXhigh: '极高',
		    effortMax: '最大',
		    options: '额外选项',
		    fast: 'Fast',
		    model: '模型',
		    using: '将使用',
		    modelCustom: '或输入完整模型 id',
		    modelApply: '应用',
		    pickerPending: '还没应用，下一轮仍用当前已保存的模型。',
		    modelUnavailable: '现在不能改这项设置。请重启 DeepSeek Harness 后再试。',
		    saveFailed: '没保存成功。请确认已经重启过 DeepSeek Harness，再点一次应用。',
		};
		const en = {
		    nav: 'Cursor subagent',
		    title: 'Cursor subagent',
		    intro: 'Use the Cursor CLI already signed in on this machine as a subagent. The chat stays in DeepSeek Harness; the job goes to Cursor. This is not a Cursor row in the model picker, and it is not an official Cursor product.',
		    proxyHint: 'Behind a proxy (common in mainland China): the browser proxy does not apply to agent / dsh. Set HTTPS_PROXY and NODE_USE_ENV_PROXY=1 in the same terminal, then log in and start. See the README section “Mainland China / proxy”.',
		    found: 'Cursor CLI found. The chat can see the cursor_agent tool. Finding the CLI is not the same as being signed in.',
		    missing: 'Cursor CLI not found. Install it, sign in, then restart DeepSeek Harness.',
		    installWin: 'PowerShell install: irm \'https://cursor.com/install?win32=true\' | iex',
		    installUnix: 'Install: curl https://cursor.com/install -fsS | bash',
		    login: 'You still need agent login (or CURSOR_API_KEY). A job fails if you are not signed in, or if the proxy is missing.',
		    signedIn: 'Signed in. The chat can run cursor_agent.',
		    signedOut: 'The CLI is here, but you are not signed in. Run agent login (or set CURSOR_API_KEY), then restart DeepSeek Harness.',
		    loginUnknown: 'Could not check sign-in. If a job fails, run agent status in a terminal. Behind a proxy, set the proxy first.',
		    proxyMissing: 'This process has no HTTPS_PROXY. A browser proxy does not count. In mainland China, set the proxy and NODE_USE_ENV_PROXY=1 in the same window that starts dsh.',
		    proxyPartial: 'A proxy URL is set, but NODE_USE_ENV_PROXY=1 is not, so Node may still go direct.',
		    proxyClashDirect: 'Clash may send node.exe DIRECT, so the child may skip the proxy. Let node.exe / agent use the proxy; do not set them to DIRECT.',
		    hostPluginMissing: 'This dsh build cannot load the official subagent packages, so cursor_agent is not registered. You need a dsh that ships @deepseek-ai/dsh-subagent-acp and dsh-tool-subagent.',
		    probe: 'Test',
		    probeHelp: 'Sends one read-only mini job (official agent --print --mode ask, reply pong). Uses a little Cursor quota.',
		    probeRunning: 'Testing…',
		    probeOk: 'It works. The CLI is signed in and can reach Cursor.',
		    probeFail: 'It failed. Check the sign-in / proxy notes above, or run agent status in a terminal.',
		    probeMissing: 'The CLI is not here, so the test cannot run.',
		    probeSignedOut: 'Not signed in, so the test cannot run. Run agent login first.',
		    probeTimeout: 'No result in time. Behind a proxy, set the proxy and try again.',
		    command: 'Executable',
		    loading: 'Checking…',
		    failed: 'Could not read status.',
		    picker: 'Subagent model',
		    pickerHelp: 'Applies only to cursor_agent. Same three controls as Cursor: effort, Fast, and model. Click Apply before the next run. auto follows the CLI default.',
		    effort: 'Effort',
		    effortLow: 'Low',
		    effortMedium: 'Medium',
		    effortHigh: 'High',
		    effortXhigh: 'Extra High',
		    effortMax: 'Max',
		    options: 'Options',
		    fast: 'Fast',
		    model: 'Model',
		    using: 'Will use',
		    modelCustom: 'Or type a full model id',
		    modelApply: 'Apply',
		    pickerPending: 'Not applied yet. The next run still uses the saved model.',
		    modelUnavailable: 'This setting cannot be changed right now. Restart DeepSeek Harness and try again.',
		    saveFailed: 'Could not save. Restart DeepSeek Harness and click Apply again.',
		};
		const { useEffect, useState } = React;
		const EFFORT_KEYS = {
		    low: 'effortLow',
		    medium: 'effortMedium',
		    high: 'effortHigh',
		    xhigh: 'effortXhigh',
		    max: 'effortMax',
		};
		function choiceFrom(status) {
		    if (status !== 'loading' && status !== 'error') {
		        return {
		            model: status.model,
		            effort: status.effort,
		            fast: status.fast,
		        };
		    }
		    return { model: 'auto', effort: 'high', fast: false };
		}
		function sameChoice(a, b) {
		    return a.model === b.model && a.effort === b.effort && a.fast === b.fast;
		}
		function previewComposed(choice, status) {
		    if (choice.model === 'auto')
		        return 'auto';
		    const family = status.families.find(item => item.id === choice.model);
		    if (family === undefined)
		        return choice.model;
		    const effort = family.efforts.includes(choice.effort)
		        ? choice.effort
		        : family.efforts.includes('high')
		            ? 'high'
		            : (family.efforts[0] ?? choice.effort);
		    const fast = family.hasFast && choice.fast;
		    const listed = family.efforts.length === 0
		        ? (fast ? `${choice.model}-fast` : choice.model)
		        : `${choice.model}-${effort}${fast ? '-fast' : ''}`;
		    if (status.models.some(item => item.id === listed))
		        return listed;
		    if (family.efforts.length > 0) {
		        return `${choice.model}[effort=${effort},fast=${fast ? 'true' : 'false'}]`;
		    }
		    return listed;
		}
		const card = {
		    marginTop: 16,
		    border: '1px solid var(--dsw-alias-border, #333)',
		    borderRadius: 10,
		    background: 'var(--dsw-alias-bg-elevated, #1e1e1e)',
		    overflow: 'hidden',
		};
		const heading = {
		    padding: '10px 12px 4px',
		    fontSize: 11,
		    letterSpacing: 0.4,
		    textTransform: 'uppercase',
		    color: 'var(--dsw-alias-text-secondary, #888)',
		};
		const row = {
		    padding: '8px 12px 12px',
		};
		const divider = {
		    height: 1,
		    background: 'var(--dsw-alias-border, #333)',
		};
		const warnText = {
		    color: 'var(--dsw-alias-danger, #c00)',
		};
		function CursorAcpSection(props) {
		    const { t, loadStatus, saveSettings, runProbe } = props;
		    const [status, setStatus] = useState('loading');
		    const [custom, setCustom] = useState('');
		    const [draft, setDraft] = useState(null);
		    const [saveError, setSaveError] = useState(false);
		    const [probe, setProbe] = useState('idle');
		    useEffect(() => {
		        let cancelled = false;
		        void loadStatus().then((next) => { if (!cancelled)
		            setStatus(next); }, () => { if (!cancelled)
		            setStatus('error'); });
		        return () => { cancelled = true; };
		    }, [loadStatus]);
		    const writable = status !== 'loading' && status !== 'error';
		    const saved = choiceFrom(status);
		    const choice = draft ?? saved;
		    const dirty = draft !== null && !sameChoice(draft, saved);
		    const families = status !== 'loading' && status !== 'error' ? status.families : [{ id: 'auto', label: 'Auto', efforts: [], hasFast: false }];
		    const family = families.find(item => item.id === choice.model) ?? families[0];
		    const efforts = family?.efforts ?? [];
		    const showEffort = choice.model !== 'auto' && efforts.length > 0;
		    const showFast = choice.model !== 'auto' && family?.hasFast === true;
		    const composed = status !== 'loading' && status !== 'error'
		        ? previewComposed(choice, status)
		        : choice.model;
		    const setField = (field, value) => {
		        setDraft({ ...choice, [field]: value });
		    };
		    const applyChoice = (next) => {
		        void (async () => {
		            try {
		                const savedNext = await saveSettings(next);
		                setStatus(savedNext);
		                setDraft(null);
		                setSaveError(false);
		            }
		            catch {
		                setSaveError(true);
		            }
		        })();
		    };
		    return (React.createElement("section", { style: { maxWidth: 640, padding: '8px 0' } },
		        React.createElement("h2", { style: { fontSize: 18, margin: '0 0 8px' } }, t('title')),
		        React.createElement("p", { style: { margin: '0 0 12px', lineHeight: 1.5 } }, t('intro')),
		        React.createElement("p", { style: { margin: '0 0 12px', lineHeight: 1.5 } }, t('proxyHint')),
		        status === 'loading' ? React.createElement("p", null, t('loading')) : null,
		        status === 'error' ? React.createElement("p", { style: { color: 'var(--dsw-alias-danger, #c00)' } }, t('failed')) : null,
		        status !== 'loading' && status !== 'error' ? (React.createElement(React.Fragment, null,
		            React.createElement("p", null, status.found ? t('found') : t('missing')),
		            status.command !== undefined ? (React.createElement("p", null,
		                t('command'),
		                ': ',
		                React.createElement("code", null, status.command))) : null,
		            status.found ? (React.createElement(React.Fragment, null,
		                React.createElement("p", { style: status.login === 'signed-in' ? undefined : warnText }, status.login === 'signed-in' ? t('signedIn') : status.login === 'signed-out' ? t('signedOut') : t('loginUnknown')),
		                status.proxy === 'set' || status.login === 'signed-in' ? null : (React.createElement("p", { style: warnText }, status.proxy === 'partial' ? t('proxyPartial') : t('proxyMissing'))),
		                status.clashDirectNode === true ? React.createElement("p", { style: warnText }, t('proxyClashDirect')) : null,
		                status.hostPluginError !== undefined ? React.createElement("p", { style: warnText }, t('hostPluginMissing')) : null,
		                React.createElement("p", { style: { margin: '12px 0 6px', lineHeight: 1.5 } }, t('probeHelp')),
		                React.createElement("button", { type: "button", disabled: !writable || probe === 'running', onClick: () => {
		                        setProbe('running');
		                        void runProbe().then((next) => setProbe(next.kind), () => setProbe('failed'));
		                    } }, probe === 'running' ? t('probeRunning') : t('probe')),
		                probe === 'ok' ? React.createElement("p", null, t('probeOk')) : null,
		                probe === 'failed' ? React.createElement("p", { style: warnText }, t('probeFail')) : null,
		                probe === 'missing-cli' ? React.createElement("p", { style: warnText }, t('probeMissing')) : null,
		                probe === 'signed-out' ? React.createElement("p", { style: warnText }, t('probeSignedOut')) : null,
		                probe === 'timeout' ? React.createElement("p", { style: warnText }, t('probeTimeout')) : null)) : (React.createElement("p", null, t('login'))),
		            React.createElement("h3", { style: { fontSize: 15, margin: '20px 0 6px' } }, t('picker')),
		            React.createElement("p", { style: { margin: '0 0 8px', lineHeight: 1.5 } }, t('pickerHelp')),
		            React.createElement("div", { style: card },
		                showEffort ? (React.createElement(React.Fragment, null,
		                    React.createElement("div", { style: heading }, t('effort')),
		                    React.createElement("div", { style: { ...row, display: 'flex', flexWrap: 'wrap', gap: 8 } }, efforts.map((effort) => {
		                        const selected = choice.effort === effort;
		                        const key = EFFORT_KEYS[effort] ?? 'effortHigh';
		                        return (React.createElement("button", { key: effort, type: "button", disabled: !writable, onClick: () => setField('effort', effort), style: {
		                                padding: '6px 12px',
		                                borderRadius: 8,
		                                border: selected
		                                    ? '1px solid var(--dsw-alias-accent, #5BB73B)'
		                                    : '1px solid var(--dsw-alias-border, #444)',
		                                background: selected ? 'color-mix(in srgb, var(--dsw-alias-accent, #5BB73B) 18%, transparent)' : 'transparent',
		                                color: 'var(--dsw-alias-text, inherit)',
		                                cursor: writable ? 'pointer' : 'default',
		                            } },
		                            t(key),
		                            selected ? ' ✓' : ''));
		                    })),
		                    React.createElement("div", { style: divider }))) : null,
		                showFast ? (React.createElement(React.Fragment, null,
		                    React.createElement("div", { style: heading }, t('options')),
		                    React.createElement("label", { style: { ...row, display: 'flex', alignItems: 'center', justifyContent: 'space-between' } },
		                        React.createElement("span", null, t('fast')),
		                        React.createElement("input", { type: "checkbox", role: "switch", checked: choice.fast, disabled: !writable, onChange: event => setField('fast', event.target.checked) })),
		                    React.createElement("div", { style: divider }))) : null,
		                React.createElement("div", { style: heading }, t('model')),
		                React.createElement("div", { style: row },
		                    React.createElement("select", { value: choice.model, disabled: !writable, onChange: event => setField('model', event.target.value), style: { width: '100%', padding: '6px 8px' } }, families.map(item => (React.createElement("option", { key: item.id, value: item.id }, item.label)))),
		                    React.createElement("div", { style: { marginTop: 8, display: 'flex', gap: 8, alignItems: 'center' } },
		                        React.createElement("p", { style: { margin: 0, flex: 1, fontSize: 12, color: 'var(--dsw-alias-text-secondary, #888)' } },
		                            t('using'),
		                            ': ',
		                            React.createElement("code", null, composed)),
		                        React.createElement("button", { type: "button", disabled: !writable || !dirty, onClick: () => applyChoice(choice) }, t('modelApply'))),
		                    dirty ? (React.createElement("p", { style: { margin: '8px 0 0', fontSize: 12, color: 'var(--dsw-alias-text-secondary, #888)' } }, t('pickerPending'))) : null)),
		            React.createElement("div", { style: { marginTop: 10, display: 'flex', gap: 8, alignItems: 'center' } },
		                React.createElement("input", { "aria-label": t('modelCustom'), placeholder: t('modelCustom'), value: custom, disabled: !writable, onChange: event => setCustom(event.target.value), style: { flex: 1, minWidth: 180, padding: '4px 8px' } }),
		                React.createElement("button", { type: "button", disabled: !writable || custom.trim() === '', onClick: () => {
		                        const next = custom.trim();
		                        setCustom('');
		                        applyChoice({ model: next, effort: choice.effort, fast: choice.fast });
		                    } }, t('modelApply'))),
		            saveError ? React.createElement("p", { style: { marginTop: 8, color: 'var(--dsw-alias-danger, #c00)' } }, t('saveFailed')) : null,
		            status.found ? null : (React.createElement("p", null, t(typeof navigator !== 'undefined' && /Win/i.test(navigator.platform) ? 'installWin' : 'installUnix'))))) : null));
		}
		const name = 'dsh-cursor-acp-client';
		const inject = ['slots', 'locale'];
		const NS = 'settings.cursor-acp';
		const STATUS_PATH = '/plugins/dsh-cursor-acp/status';
		const PROBE_PATH = '/plugins/dsh-cursor-acp/probe';
		async function loadStatus() {
		    const response = await fetch(STATUS_PATH, { headers: { accept: 'application/json' } });
		    if (!response.ok)
		        throw new Error(`status ${String(response.status)}`);
		    return await response.json();
		}
		async function saveSettings(next) {
		    const response = await fetch(STATUS_PATH, {
		        method: 'POST',
		        headers: { accept: 'application/json', 'content-type': 'application/json' },
		        body: JSON.stringify(next),
		    });
		    if (!response.ok)
		        throw new Error(`save ${String(response.status)}`);
		    return await response.json();
		}
		async function runProbe() {
		    const response = await fetch(PROBE_PATH, {
		        method: 'POST',
		        headers: { accept: 'application/json' },
		    });
		    if (!response.ok)
		        throw new Error(`probe ${String(response.status)}`);
		    return await response.json();
		}
		function apply(ctx) {
		    ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'dsh-cursor-acp: dictionaries');
		    const t = ctx.locale.bind(NS);
		    ctx.slots.inject('settings.section', () => ctx.slots.register({
		        name: 'settings.section',
		        id: 'cursor-acp',
		        order: 26,
		        label: () => t('nav'),
		        locale: NS,
		        inject: () => ({
		            t: (key) => t(key),
		            loadStatus,
		            saveSettings,
		            runProbe,
		        }),
		    }, CursorAcpSection));
		}
		exports.name = name;
		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
