/* generated by scripts/emit.mjs — edit src/client, not this file */
window.__ModuleLoader__.load({
	id: "dsh-cursor-acp",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		const React = require("react");
		const zh = {
		    nav: 'Cursor 子代理',
		    intro: '把本机已登录的 Cursor 命令行当成子代理。对话还在 DeepSeek Harness，任务会交给 Cursor。这不是模型列表里的「Cursor 模型」，也不是 Cursor 官方产品。',
		    proxyHint: '国内请注意：浏览器开了代理，终端里的 agent / dsh 默认仍直连。先在同一窗口设置 HTTPS_PROXY 和 NODE_USE_ENV_PROXY=1，再登录、再启动。详见项目 README「国内网络」。',
		    stateReady: '已就绪：cursor_agent 可以正常使用。',
		    stateWarn: '命令行已找到，但登录 / 代理还有问题要处理。',
		    stateMissingCli: '未找到 Cursor 命令行，cursor_agent 未挂载。',
		    stateBrokenHost: '宿主 dsh 缺少官方子代理包，cursor_agent 未挂载。',
		    detailExec: '可执行文件',
		    detailLogin: '登录状态',
		    detailProxy: '代理',
		    detailClash: 'Clash 直连',
		    detailHostPlugin: '宿主插件',
		    logOk: '已登录',
		    logOut: '未登录',
		    logUnknown: '未知',
		    proxySet: '已设置',
		    proxyPartial: '缺 NODE_USE_ENV_PROXY=1，Node 可能仍直连',
		    proxyMissing: '未设置（浏览器代理不算）',
		    clashOn: 'node.exe 可能被设为直连，子进程可能没走代理',
		    missingCliRow: '未找到',
		    installWin: 'PowerShell 安装：irm \'https://cursor.com/install?win32=true\' | iex',
		    installUnix: '安装：curl https://cursor.com/install -fsS | bash',
		    loginCmdHint: '随后在本机终端执行 agent login（或设置 CURSOR_API_KEY），再重启 DeepSeek Harness。',
		    netDetails: '国内网络说明',
		    loading: '正在检测…',
		    failed: '无法读取状态。',
		    probeSection: '连通性测试',
		    probe: '测一下',
		    probeHelp: '派一个只读的最小任务（官方 agent --print --mode ask，回复 pong）。会用一点 Cursor 额度。',
		    probeRunning: '正在测…',
		    probeOk: '通了。命令行已登录，也能接到 Cursor。',
		    probeFail: '不通。请看上方状态里的登录 / 代理提示，或在终端跑 agent status。',
		    probeMissing: '还没找到命令行，没法测。',
		    probeSignedOut: '还没登录，测不了。请先 agent login。',
		    probeTimeout: '等太久没有结果。国内请先检查代理，再点一次。',
		    picker: '子代理模型',
		    pickerHelp: '只影响 cursor_agent。选法和 Cursor 一样：思考程度、Fast、模型。改完点「应用」，下一轮才会换。auto 跟 CLI 默认走。',
		    using: '将使用',
		    live: '已生效',
		    pendingBadge: '未应用',
		    effort: '思考程度',
		    effortLow: '低',
		    effortMedium: '中',
		    effortHigh: '高',
		    effortXhigh: '极高',
		    effortMax: '最大',
		    options: '额外选项',
		    fast: 'Fast',
		    model: '模型',
		    customHeading: '自定义模型 id',
		    modelCustom: '或输入完整模型 id',
		    modelApply: '应用',
		    undo: '撤销',
		    saving: '正在保存…',
		    applied: '已应用，下一轮生效。',
		    saveFailed: '没保存成功。请确认 dsh 已带官方子代理包，再点一次应用。',
		};
		const en = {
		    nav: 'Cursor subagent',
		    intro: 'Use the Cursor CLI already signed in on this machine as a subagent. The chat stays in DeepSeek Harness; the job goes to Cursor. This is not a Cursor row in the model picker, and it is not an official Cursor product.',
		    proxyHint: 'Behind a proxy (common in mainland China): the browser proxy does not apply to agent / dsh. Set HTTPS_PROXY and NODE_USE_ENV_PROXY=1 in the same terminal, then log in and start. See the README section “Mainland China / proxy”.',
		    stateReady: 'Ready: cursor_agent is fully usable.',
		    stateWarn: 'CLI found, but sign-in / proxy needs attention.',
		    stateMissingCli: 'Cursor CLI not found — cursor_agent is not registered.',
		    stateBrokenHost: 'This dsh build cannot load the official subagent packages — cursor_agent is not registered.',
		    detailExec: 'Executable',
		    detailLogin: 'Sign-in',
		    detailProxy: 'Proxy',
		    detailClash: 'Clash direct',
		    detailHostPlugin: 'Host plugin',
		    logOk: 'Signed in',
		    logOut: 'Not signed in',
		    logUnknown: 'Unknown',
		    proxySet: 'Set',
		    proxyPartial: 'Missing NODE_USE_ENV_PROXY=1 — Node may still go direct',
		    proxyMissing: 'Not set (a browser proxy does not count)',
		    clashOn: 'node.exe may be forced DIRECT, so the child may skip the proxy',
		    missingCliRow: 'Not found',
		    installWin: 'PowerShell install: irm \'https://cursor.com/install?win32=true\' | iex',
		    installUnix: 'Install: curl https://cursor.com/install -fsS | bash',
		    loginCmdHint: 'Then run agent login (or set CURSOR_API_KEY) in a terminal and restart DeepSeek Harness.',
		    netDetails: 'Mainland China / proxy notes',
		    loading: 'Checking…',
		    failed: 'Could not read status.',
		    probeSection: 'Connectivity test',
		    probe: 'Test',
		    probeHelp: 'Sends one read-only mini job (official agent --print --mode ask, reply pong). Uses a little Cursor quota.',
		    probeRunning: 'Testing…',
		    probeOk: 'It works. The CLI is signed in and can reach Cursor.',
		    probeFail: 'It failed. Check the sign-in / proxy notes above, or run agent status in a terminal.',
		    probeMissing: 'The CLI is not here, so the test cannot run.',
		    probeSignedOut: 'Not signed in, so the test cannot run. Run agent login first.',
		    probeTimeout: 'No result in time. Behind a proxy, set the proxy and try again.',
		    picker: 'Subagent model',
		    pickerHelp: 'Applies only to cursor_agent. Same three controls as Cursor: effort, Fast, and model. Click Apply before the next run. auto follows the CLI default.',
		    using: 'Will use',
		    live: 'Live',
		    pendingBadge: 'Pending',
		    effort: 'Effort',
		    effortLow: 'Low',
		    effortMedium: 'Medium',
		    effortHigh: 'High',
		    effortXhigh: 'Extra High',
		    effortMax: 'Max',
		    options: 'Options',
		    fast: 'Fast',
		    model: 'Model',
		    customHeading: 'Custom model id',
		    modelCustom: 'Or type a full model id',
		    modelApply: 'Apply',
		    undo: 'Undo',
		    saving: 'Saving…',
		    applied: 'Applied — takes effect next run.',
		    saveFailed: 'Could not save. Make sure this dsh ships the official subagent packages, then click Apply again.',
		};
		const { useEffect, useState } = React;
		const EFFORT_KEYS = {
		    low: 'effortLow',
		    medium: 'effortMedium',
		    high: 'effortHigh',
		    xhigh: 'effortXhigh',
		    max: 'effortMax',
		};
		const toneColor = {
		    ok: 'var(--dsw-alias-state-success-primary)',
		    warn: 'var(--dsw-alias-state-warn-primary)',
		    error: 'var(--dsw-alias-state-error-primary)',
		    neutral: 'var(--dsw-alias-border-l2)',
		};
		const toneText = {
		    ok: 'var(--dsw-alias-state-success-primary)',
		    warn: 'var(--dsw-alias-state-warn-label)',
		    error: 'var(--dsw-alias-state-error-primary)',
		};
		function choiceFrom(status) {
		    if (status !== 'loading' && status !== 'error') {
		        return {
		            model: status.model,
		            effort: status.effort,
		            fast: status.fast,
		        };
		    }
		    return { model: 'auto', effort: 'high', fast: false };
		}
		function sameChoice(a, b) {
		    return a.model === b.model && a.effort === b.effort && a.fast === b.fast;
		}
		function previewComposed(choice, status) {
		    if (choice.model === 'auto')
		        return 'auto';
		    const family = status.families.find(item => item.id === choice.model);
		    if (family === undefined)
		        return choice.model;
		    const effort = family.efforts.includes(choice.effort)
		        ? choice.effort
		        : family.efforts.includes('high')
		            ? 'high'
		            : (family.efforts[0] ?? choice.effort);
		    const fast = family.hasFast && choice.fast;
		    const listed = family.efforts.length === 0
		        ? (fast ? `${choice.model}-fast` : choice.model)
		        : `${choice.model}-${effort}${fast ? '-fast' : ''}`;
		    if (status.models.some(item => item.id === listed))
		        return listed;
		    if (family.efforts.length > 0) {
		        return `${choice.model}[effort=${effort},fast=${fast ? 'true' : 'false'}]`;
		    }
		    return listed;
		}
		function overallOf(status) {
		    if (!status.found || status.hostPluginError !== undefined)
		        return 'error';
		    if (status.login === 'signed-in' && status.proxy === 'set' && status.clashDirectNode !== true)
		        return 'ok';
		    return 'warn';
		}
		const card = {
		    marginTop: 16,
		    border: '1px solid var(--dsw-alias-border-l2)',
		    borderRadius: 10,
		    background: 'var(--dsw-alias-bg-layer-1)',
		    overflow: 'hidden',
		};
		const heading = {
		    padding: '10px 12px 4px',
		    fontSize: 11,
		    letterSpacing: 0.4,
		    textTransform: 'uppercase',
		    color: 'var(--dsw-alias-label-tertiary)',
		};
		const row = {
		    padding: '8px 12px 12px',
		};
		const divider = {
		    height: 1,
		    background: 'var(--dsw-alias-border-l2)',
		};
		const helpText = {
		    margin: '0 0 8px',
		    fontSize: 13,
		    lineHeight: 1.6,
		    color: 'var(--dsw-alias-label-secondary)',
		};
		const codeStyle = {
		    fontSize: 12,
		    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
		    background: 'color-mix(in srgb, var(--dsw-alias-label-secondary) 10%, transparent)',
		    padding: '1px 5px',
		    borderRadius: 5,
		    wordBreak: 'break-all',
		};
		const buttonBase = {
		    padding: '6px 14px',
		    borderRadius: 8,
		    fontSize: 13,
		    border: '1px solid transparent',
		    cursor: 'pointer',
		    fontFamily: 'inherit',
		};
		const pendingBadge = {
		    fontSize: 11,
		    padding: '2px 8px',
		    borderRadius: 999,
		    color: 'var(--dsw-alias-state-warn-label)',
		    background: 'color-mix(in srgb, var(--dsw-alias-state-warn-primary) 14%, transparent)',
		    whiteSpace: 'nowrap',
		};
		const liveBadge = {
		    fontSize: 11,
		    padding: '2px 8px',
		    borderRadius: 999,
		    color: 'var(--dsw-alias-state-success-primary)',
		    background: 'color-mix(in srgb, var(--dsw-alias-state-success-primary) 12%, transparent)',
		    whiteSpace: 'nowrap',
		};
		function StatusDot({ tone }) {
		    return (React.createElement("span", { "aria-hidden": true, style: {
		            width: 8,
		            height: 8,
		            borderRadius: '50%',
		            background: toneColor[tone],
		            flexShrink: 0,
		            marginTop: 6,
		        } }));
		}
		function DetailRow({ label, tone, children }) {
		    return (React.createElement("div", { style: { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '5px 0' } },
		        React.createElement(StatusDot, { tone: tone }),
		        React.createElement("div", { style: { flex: 1, minWidth: 0 } },
		            React.createElement("div", { style: { fontSize: 12, color: 'var(--dsw-alias-label-tertiary)' } }, label),
		            React.createElement("div", { style: { fontSize: 13, color: 'var(--dsw-alias-label-primary)', marginTop: 1, wordBreak: 'break-word' } }, children))));
		}
		const probeTone = {
		    ok: 'ok',
		    failed: 'error',
		    'missing-cli': 'error',
		    'signed-out': 'error',
		    timeout: 'warn',
		};
		const probeResultKey = {
		    ok: 'probeOk',
		    failed: 'probeFail',
		    'missing-cli': 'probeMissing',
		    'signed-out': 'probeSignedOut',
		    timeout: 'probeTimeout',
		};
		function CursorAcpSection(props) {
		    const { t, loadStatus, saveSettings, runProbe } = props;
		    const [status, setStatus] = useState('loading');
		    const [custom, setCustom] = useState('');
		    const [draft, setDraft] = useState(null);
		    const [saveError, setSaveError] = useState(false);
		    const [saving, setSaving] = useState(false);
		    const [appliedFlash, setAppliedFlash] = useState(false);
		    const [probe, setProbe] = useState('idle');
		    const [open, setOpen] = useState(false);
		    useEffect(() => {
		        let cancelled = false;
		        void loadStatus().then((next) => { if (!cancelled)
		            setStatus(next); }, () => { if (!cancelled)
		            setStatus('error'); });
		        return () => { cancelled = true; };
		    }, [loadStatus]);
		    const statusView = status !== 'loading' && status !== 'error' ? status : null;
		    const writable = statusView !== null && !saving;
		    const saved = choiceFrom(status);
		    const choice = draft ?? saved;
		    const dirty = draft !== null && !sameChoice(draft, saved);
		    const families = statusView !== null ? statusView.families : [{ id: 'auto', label: 'Auto', efforts: [], hasFast: false }];
		    const family = families.find(item => item.id === choice.model) ?? families[0];
		    const efforts = family?.efforts ?? [];
		    const showEffort = choice.model !== 'auto' && efforts.length > 0;
		    const showFast = choice.model !== 'auto' && family?.hasFast === true;
		    const composed = statusView !== null ? previewComposed(choice, statusView) : choice.model;
		    const isWindows = typeof navigator !== 'undefined' && /Win/i.test(navigator.platform);
		    const setField = (field, value) => {
		        setDraft({ ...choice, [field]: value });
		    };
		    const applyChoice = (next) => {
		        void (async () => {
		            setSaving(true);
		            setSaveError(false);
		            try {
		                const savedNext = await saveSettings(next);
		                setStatus(savedNext);
		                setDraft(null);
		                setAppliedFlash(true);
		                window.setTimeout(() => setAppliedFlash(false), 3000);
		            }
		            catch {
		                setSaveError(true);
		            }
		            finally {
		                setSaving(false);
		            }
		        })();
		    };
		    const over = statusView !== null ? overallOf(statusView) : 'warn';
		    const conclusion = statusView !== null
		        ? !statusView.found
		            ? t('stateMissingCli')
		            : statusView.hostPluginError !== undefined
		                ? t('stateBrokenHost')
		                : over === 'ok'
		                    ? t('stateReady')
		                    : t('stateWarn')
		        : '';
		    const loginTone = statusView?.login === 'signed-in' ? 'ok' : statusView?.login === 'signed-out' ? 'error' : 'warn';
		    const loginText = statusView?.login === 'signed-in' ? t('logOk') : statusView?.login === 'signed-out' ? t('logOut') : t('logUnknown');
		    const proxyTone = statusView?.proxy === 'set' ? 'ok' : statusView?.proxy === 'partial' ? 'warn' : 'error';
		    const proxyText = statusView?.proxy === 'set' ? t('proxySet') : statusView?.proxy === 'partial' ? t('proxyPartial') : t('proxyMissing');
		    // One card inside the Plugins → configurable settings tab, collapsible like
		    // the other plugin cards around it. Staged edits outlive collapsing.
		    return (React.createElement("li", { style: {
		            listStyle: 'none',
		            border: '1px solid var(--dsw-alias-border-l2)',
		            borderRadius: 12,
		            background: open ? 'var(--dsw-alias-bg-layer-2)' : 'var(--dsw-alias-bg-layer-3)',
		            transition: 'border-color .16s, background .16s',
		        } },
		        React.createElement("button", { type: "button", "aria-expanded": open, onClick: () => { setOpen(!open); }, style: {
		                width: '100%',
		                appearance: 'none',
		                border: 0,
		                background: 'none',
		                font: 'inherit',
		                color: 'inherit',
		                textAlign: 'left',
		                cursor: 'pointer',
		                display: 'flex',
		                alignItems: 'center',
		                gap: 12,
		                padding: '14px 16px',
		                borderRadius: 12,
		            } },
		            React.createElement("span", { style: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 4 } },
		                React.createElement("span", { style: { fontSize: 15, fontWeight: 600, lineHeight: 1.4, color: 'var(--dsw-alias-label-primary)' } }, t('nav')),
		                React.createElement("span", { style: { fontSize: 13, lineHeight: 1.5, color: 'var(--dsw-alias-label-tertiary)' } }, t('intro'))),
		            dirty ? (React.createElement("span", { style: {
		                    flex: 'none',
		                    borderRadius: 999,
		                    padding: '1px 8px',
		                    fontSize: 11,
		                    lineHeight: '17px',
		                    fontWeight: 500,
		                    whiteSpace: 'nowrap',
		                    background: 'var(--dsw-alias-bg-module-platform)',
		                    color: 'var(--dsw-alias-label-secondary)',
		                } }, t('pendingBadge'))) : null,
		            React.createElement("svg", { width: "14", height: "14", viewBox: "0 0 14 14", "aria-hidden": true, style: {
		                    flex: 'none',
		                    color: 'var(--dsw-alias-label-tertiary)',
		                    transition: 'transform .16s',
		                    transform: open ? 'rotate(180deg)' : undefined,
		                } },
		                React.createElement("path", { d: "M3.5 5.5 7 9l3.5-3.5", fill: "none", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round", strokeLinejoin: "round" }))),
		        open ? (React.createElement("div", { style: { borderTop: '1px solid var(--dsw-alias-border-l2)', margin: '0 16px', paddingBottom: 8 } },
		            statusView === null ? (React.createElement("p", { style: { margin: 0, fontSize: 13, color: 'var(--dsw-alias-label-secondary)' } }, status === 'error' ? React.createElement("span", { style: { color: 'var(--dsw-alias-state-error-primary)' } }, t('failed')) : t('loading'))) : (React.createElement(React.Fragment, null,
		                React.createElement("div", { style: {
		                        marginTop: 0,
		                        border: '1px solid var(--dsw-alias-border-l2)',
		                        borderLeft: `3px solid ${toneColor[over]}`,
		                        borderRadius: 10,
		                        background: `color-mix(in srgb, ${toneColor[over]} 7%, transparent)`,
		                        overflow: 'hidden',
		                    } },
		                    React.createElement("div", { style: { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '12px 14px' } },
		                        React.createElement(StatusDot, { tone: over }),
		                        React.createElement("strong", { style: { fontSize: 14, lineHeight: 1.55 } }, conclusion)),
		                    React.createElement("div", { style: { padding: '0 14px 10px', borderTop: '1px solid var(--dsw-alias-border-l2)' } }, statusView.found ? (React.createElement(React.Fragment, null,
		                        React.createElement(DetailRow, { label: t('detailExec'), tone: "neutral" }, statusView.command !== undefined ? React.createElement("code", { style: codeStyle }, statusView.command) : '—'),
		                        React.createElement(DetailRow, { label: t('detailLogin'), tone: loginTone }, loginText),
		                        React.createElement(DetailRow, { label: t('detailProxy'), tone: proxyTone }, proxyText),
		                        statusView.clashDirectNode === true ? (React.createElement(DetailRow, { label: t('detailClash'), tone: "warn" }, t('clashOn'))) : null,
		                        statusView.hostPluginError !== undefined ? (React.createElement(DetailRow, { label: t('detailHostPlugin'), tone: "error" },
		                            React.createElement("code", { style: codeStyle }, statusView.hostPluginError))) : null)) : (React.createElement(React.Fragment, null,
		                        React.createElement(DetailRow, { label: t('detailExec'), tone: "error" }, t('missingCliRow')),
		                        React.createElement("p", { style: { margin: '8px 0 0', fontSize: 13, lineHeight: 1.6 } },
		                            React.createElement("code", { style: codeStyle }, isWindows ? t('installWin') : t('installUnix'))),
		                        React.createElement("p", { style: { margin: '6px 0 0', fontSize: 13, lineHeight: 1.6, color: 'var(--dsw-alias-label-secondary)' } }, t('loginCmdHint'))))),
		                    React.createElement("details", { style: { borderTop: '1px solid var(--dsw-alias-border-l2)' } },
		                        React.createElement("summary", { style: { padding: '10px 14px', cursor: 'pointer', fontSize: 12, color: 'var(--dsw-alias-label-secondary)' } }, t('netDetails')),
		                        React.createElement("p", { style: { margin: 0, padding: '0 14px 12px', fontSize: 12.5, lineHeight: 1.65, color: 'var(--dsw-alias-label-secondary)' } }, t('proxyHint')))),
		                statusView.found ? (React.createElement(React.Fragment, null,
		                    React.createElement("h3", { style: { fontSize: 15, margin: '16px 0 6px' } }, t('probeSection')),
		                    React.createElement("p", { style: helpText }, t('probeHelp')),
		                    React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' } },
		                        React.createElement("button", { type: "button", disabled: probe === 'running', onClick: () => {
		                                setProbe('running');
		                                void runProbe().then((next) => setProbe(next.kind), () => setProbe('failed'));
		                            }, style: {
		                                ...buttonBase,
		                                borderColor: 'var(--dsw-alias-border-l2)',
		                                background: 'transparent',
		                                color: 'var(--dsw-alias-label-primary)',
		                                opacity: probe === 'running' ? 0.6 : 1,
		                                cursor: probe === 'running' ? 'default' : 'pointer',
		                            } }, probe === 'running' ? t('probeRunning') : t('probe')),
		                        probe !== 'idle' && probe !== 'running' ? (React.createElement("span", { style: { display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 13, color: toneText[probeTone[probe]] } },
		                            React.createElement(StatusDot, { tone: probeTone[probe] }),
		                            t(probeResultKey[probe]))) : null))) : null,
		                React.createElement("h3", { style: { fontSize: 15, margin: '16px 0 6px' } }, t('picker')),
		                React.createElement("p", { style: helpText }, t('pickerHelp')),
		                React.createElement("div", { style: card },
		                    React.createElement("div", { style: { display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderBottom: '1px solid var(--dsw-alias-border-l2)', flexWrap: 'wrap' } },
		                        React.createElement("span", { style: { fontSize: 12, color: 'var(--dsw-alias-label-secondary)' } }, t('using')),
		                        React.createElement("code", { style: { fontSize: 13, color: 'var(--dsw-alias-label-primary)' } }, composed),
		                        dirty ? React.createElement("span", { style: pendingBadge }, t('pendingBadge')) : React.createElement("span", { style: liveBadge }, t('live'))),
		                    showEffort ? (React.createElement(React.Fragment, null,
		                        React.createElement("div", { style: heading }, t('effort')),
		                        React.createElement("div", { style: { ...row, display: 'flex', flexWrap: 'wrap', gap: 8 } }, efforts.map((effort) => {
		                            const selected = choice.effort === effort;
		                            const key = EFFORT_KEYS[effort] ?? 'effortHigh';
		                            return (React.createElement("button", { key: effort, type: "button", disabled: !writable, onClick: () => setField('effort', effort), style: {
		                                    ...buttonBase,
		                                    padding: '6px 12px',
		                                    borderColor: selected
		                                        ? 'var(--dsw-alias-state-business-primary)'
		                                        : 'var(--dsw-alias-border-l2)',
		                                    background: selected ? 'color-mix(in srgb, var(--dsw-alias-state-business-primary) 18%, transparent)' : 'transparent',
		                                    color: 'var(--dsw-alias-label-primary)',
		                                    opacity: writable ? 1 : 0.6,
		                                    cursor: writable ? 'pointer' : 'default',
		                                } },
		                                t(key),
		                                selected ? ' ✓' : ''));
		                        })),
		                        React.createElement("div", { style: divider }))) : null,
		                    showFast ? (React.createElement(React.Fragment, null,
		                        React.createElement("div", { style: heading }, t('options')),
		                        React.createElement("label", { style: { ...row, display: 'flex', alignItems: 'center', justifyContent: 'space-between' } },
		                            React.createElement("span", null, t('fast')),
		                            React.createElement("input", { type: "checkbox", role: "switch", checked: choice.fast, disabled: !writable, onChange: event => setField('fast', event.target.checked) })),
		                        React.createElement("div", { style: divider }))) : null,
		                    React.createElement("div", { style: heading }, t('model')),
		                    React.createElement("div", { style: row },
		                        React.createElement("select", { value: choice.model, disabled: !writable, onChange: event => setField('model', event.target.value), style: {
		                                width: '100%',
		                                padding: '6px 8px',
		                                border: '1px solid var(--dsw-alias-border-l2)',
		                                borderRadius: 6,
		                                background: 'var(--dsw-alias-bg-layer-1)',
		                                color: 'var(--dsw-alias-label-primary)',
		                            } }, families.map(item => (React.createElement("option", { key: item.id, value: item.id }, item.label))))),
		                    React.createElement("div", { style: divider }),
		                    React.createElement("div", { style: heading }, t('customHeading')),
		                    React.createElement("div", { style: { ...row, display: 'flex', gap: 8, alignItems: 'stretch' } },
		                        React.createElement("input", { "aria-label": t('modelCustom'), placeholder: t('modelCustom'), value: custom, disabled: !writable, onChange: event => setCustom(event.target.value), style: {
		                                flex: 1,
		                                minWidth: 180,
		                                padding: '4px 8px',
		                                border: '1px solid var(--dsw-alias-border-l2)',
		                                borderRadius: 6,
		                                background: 'var(--dsw-alias-bg-layer-1)',
		                                color: 'var(--dsw-alias-label-primary)',
		                            } }),
		                        React.createElement("button", { type: "button", disabled: !writable || custom.trim() === '', onClick: () => {
		                                const next = custom.trim();
		                                setCustom('');
		                                applyChoice({ model: next, effort: choice.effort, fast: choice.fast });
		                            }, style: {
		                                ...buttonBase,
		                                borderColor: 'var(--dsw-alias-border-l2)',
		                                background: 'transparent',
		                                color: 'var(--dsw-alias-label-primary)',
		                                opacity: !writable || custom.trim() === '' ? 0.5 : 1,
		                                cursor: !writable || custom.trim() === '' ? 'default' : 'pointer',
		                            } }, t('modelApply')))))),
		            React.createElement("div", { style: { display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 8, padding: '12px 0 4px', borderTop: '1px solid var(--dsw-alias-border-l2)' } },
		                appliedFlash ? React.createElement("span", { style: { flex: 1, fontSize: 12, color: toneText.ok } }, t('applied')) : null,
		                saveError ? React.createElement("span", { style: { flex: 1, fontSize: 12, color: toneText.error } }, t('saveFailed')) : null,
		                dirty ? (React.createElement("button", { type: "button", disabled: saving, onClick: () => { setDraft(null); setSaveError(false); }, style: {
		                        appearance: 'none',
		                        border: '1px solid var(--dsw-alias-border-l2)',
		                        borderRadius: 8,
		                        padding: '5px 14px',
		                        font: 'inherit',
		                        fontSize: 13,
		                        lineHeight: 1.5,
		                        background: 'none',
		                        color: 'var(--dsw-alias-label-secondary)',
		                        cursor: saving ? 'default' : 'pointer',
		                        opacity: saving ? 0.4 : 1,
		                    } }, t('undo'))) : null,
		                React.createElement("button", { type: "button", disabled: !writable || !dirty, onClick: () => applyChoice(choice), style: {
		                        appearance: 'none',
		                        border: '1px solid transparent',
		                        borderRadius: 8,
		                        padding: '5px 14px',
		                        font: 'inherit',
		                        fontSize: 13,
		                        lineHeight: 1.5,
		                        background: 'var(--dsw-alias-label-primary)',
		                        color: 'var(--dsw-alias-bg-layer-3)',
		                        cursor: !writable || !dirty ? 'default' : 'pointer',
		                        opacity: !writable || !dirty ? 0.4 : 1,
		                    } }, saving ? t('saving') : t('modelApply'))))) : null));
		}
		const name = 'dsh-cursor-acp-client';
		const inject = ['slots', 'locale'];
		const NS = 'settings.cursor-acp';
		const STATUS_PATH = '/plugins/dsh-cursor-acp/status';
		const PROBE_PATH = '/plugins/dsh-cursor-acp/probe';
		async function loadStatus() {
		    const response = await fetch(STATUS_PATH, { headers: { accept: 'application/json' } });
		    if (!response.ok)
		        throw new Error(`status ${String(response.status)}`);
		    return await response.json();
		}
		async function saveSettings(next) {
		    const response = await fetch(STATUS_PATH, {
		        method: 'POST',
		        headers: { accept: 'application/json', 'content-type': 'application/json' },
		        body: JSON.stringify(next),
		    });
		    if (!response.ok)
		        throw new Error(`save ${String(response.status)}`);
		    return await response.json();
		}
		async function runProbe() {
		    const response = await fetch(PROBE_PATH, {
		        method: 'POST',
		        headers: { accept: 'application/json' },
		    });
		    if (!response.ok)
		        throw new Error(`probe ${String(response.status)}`);
		    return await response.json();
		}
		function apply(ctx) {
		    ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'dsh-cursor-acp: dictionaries');
		    const t = ctx.locale.bind(NS);
		    // One card inside the Plugins → configurable settings tab ("插件配置").
		    // The tab dispatches cards by settings namespace; `cursor-acp` is registered
		    // host-side, so the Host's describe mirror serves it and this card appears.
		    ctx.slots.inject('settings.plugin.item', () => ctx.slots.register({
		        name: 'settings.plugin.item',
		        key: 'cursor-acp',
		        locale: NS,
		        inject: () => ({
		            t: (key) => t(key),
		            loadStatus,
		            saveSettings,
		            runProbe,
		        }),
		    }, CursorAcpSection));
		}
		exports.name = name;
		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
