import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const require = createRequire(join(root, 'package.json'))

function loadTypescript() {
  try {
    return require('typescript')
  } catch {
    console.error('dsh-cursor-acp: typescript is not installed. Run pnpm install in this package directory.')
    process.exit(1)
  }
}

const ts = loadTypescript()

const hostFiles = [
  ['src/resolve-agent.ts', 'lib/resolve-agent.js'],
  ['src/proxy-env.ts', 'lib/proxy-env.js'],
  ['src/clash-direct.ts', 'lib/clash-direct.js'],
  ['src/readiness.ts', 'lib/readiness.js'],
  ['src/status.ts', 'lib/status.js'],
  ['src/models.ts', 'lib/models.js'],
  ['src/list-models.ts', 'lib/list-models.js'],
  ['src/settings-schema.ts', 'lib/settings-schema.js'],
  ['src/import-host.ts', 'lib/import-host.js'],
  ['src/prompt.ts', 'lib/prompt.js'],
  ['src/probe.ts', 'lib/probe.js'],
  ['src/acp-config.ts', 'lib/acp-config.js'],
  ['src/index.ts', 'lib/index.js'],
  ['src/bin.ts', 'lib/bin.js'],
]

const clientFiles = [
  'src/client/locales.ts',
  'src/client/CursorAcpSection.tsx',
  'src/client/index.ts',
]

function transpile(src, jsx = ts.JsxEmit.ReactJSX) {
  const input = readFileSync(join(root, src), 'utf8')
  return ts.transpileModule(input, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2024,
      jsx,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
    },
    fileName: src,
  }).outputText
}

function rewriteRelativeImports(text) {
  return text.replaceAll(/(\.\.?\/[^'"]+)\.tsx?(?=['"])/g, '$1.js')
}

function emitHost() {
  for (const [src, dest] of hostFiles) {
    const rewritten = rewriteRelativeImports(transpile(src))
    const out = join(root, dest)
    mkdirSync(dirname(out), { recursive: true })
    const body = rewritten.replace(/^#!.*\r?\n/, '')
    writeFileSync(out, dest.endsWith('bin.js') ? `#!/usr/bin/env node\n${body}` : body)
    process.stdout.write(`wrote ${dest}\n`)
  }
}

function importedBindings(names) {
  return names.split(',').flatMap((part) => {
    const trimmed = part.trim()
    if (trimmed === '' || trimmed.startsWith('type ')) return []
    const sides = trimmed.split(/\s+as\s+/)
    return [(sides[1] ?? sides[0]).trim()]
  })
}

function stripClientModule(text) {
  return text
    .replace(/import\s+\{([^}]+)\}\s+from\s+["']react["'];?\s*/g, (_, names) => {
      return `const { ${importedBindings(names).join(', ')} } = React;\n`
    })
    .replace(/import\s+[^;]+;?\s*/g, '')
    .replace(/export\s+\{[^}]+\};?\s*/g, '')
    .replace(/^export\s+/gm, '')
}

function indentBlock(text, tabs) {
  const prefix = '\t'.repeat(tabs)
  return text.replace(/\r\n/g, '\n').trim().split('\n').map((line) => (
    line === '' ? '' : prefix + line
  )).join('\n')
}

function emitClient() {
  const parts = clientFiles.map((src) => stripClientModule(transpile(src, ts.JsxEmit.React)))
  const body = [
    '/* generated by scripts/emit.mjs — edit src/client, not this file */',
    'window.__ModuleLoader__.load({',
    '\tid: "dsh-cursor-acp",',
    '\tfactory: (require) => {',
    '\t\tvar module = { exports: {} };',
    '\t\tvar exports = module.exports;',
    '\t\tconst React = require("react");',
    ...parts.map((part) => indentBlock(part, 2)),
    '\t\texports.name = name;',
    '\t\texports.inject = inject;',
    '\t\texports.apply = apply;',
    '\t\treturn module.exports;',
    '\t}',
    '});',
    '',
  ].join('\n')
  if (!body.includes('function apply') || !body.includes('function CursorAcpSection')) {
    console.error('dsh-cursor-acp: client emit missing apply / CursorAcpSection')
    process.exit(1)
  }
  mkdirSync(join(root, 'lib'), { recursive: true })
  writeFileSync(join(root, 'lib/client.js'), body)
  process.stdout.write('wrote lib/client.js\n')
}

emitHost()
emitClient()
